name: BalenaCloud Push

on:
  push:
    branches:
      - add-balena

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install project dependencies
        run: npm install
      - name: Set Node version
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build device
        run: npm run build device
      - name: Push to Balena
        uses: amingilani/push-to-balenacloud@v1.0.1
        with:
          api-token: ${{ secrets.BALENA_API_KEY }}
          application-name: ${{ secrets.BALENA_APPLICATION_NAME }}
          application-path: "./dist/apps/device"
