name: Build and publish to Expo

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build and deploy mobile
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install project dependencies
        run: npm install
      - name: Install mobile dependencies
        run: npm install
        working-directory: ./apps/mobile
      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup expo cli
        uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - name: Build android
        run: expo build:android
        working-directory: ./apps/mobile
      # - name: Build ios
      #   run: expo build:ios
      #   working-directory: ./apps/mobile
